name: AUR Package Update with Docker

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-aur:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PUSH_CONTAINER }}

      - name: Cache Docker images.
        uses: ScribeMD/docker-cache@0.5.0
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('Dockerfile') }}-${{ hashFiles('*.sh') }}

      - name: Run updater container
        env:
          PUSH_KEY: ${{ secrets.SERVER_CHAN_SENDKEY }}
          AUR_SSH_KEY_BASE64: ${{ secrets.AUR_SSH_KEY_BASE64 }}
          USERNAME: ${{ secrets.USERNAME }}
          EMAIL: ${{ secrets.EMAIL }}
        run: |
          # 运行 Docker 容器，在容器内设置 SSH 密钥
          docker run ghcr.io/${{ github.actor }}/aur_updater:latest --rm \
            -e PUSH_KEY="$PUSH_KEY" \
            -e AUR_SSH_KEY_BASE64="$AUR_SSH_KEY_BASE64" \
            -e USERNAME="$USERNAME" \
            -e EMAIL="$EMAIL" \
            aur-updater
